export const CALC = 'CALC'
export const GET_NUM = 'GET_NUM'
export const DO_OTHER_OPER = 'DO_OTHER_OPER'
export const CHANGE_HISTORY = 'CHANGE_HISTORY'
export const CHANGE_THEME = 'CHANGE_THEME'
export const CHANGE_HIDDEN = 'CHANGE_HIDDEN'
export const CLEAN_ALL = 'CLEAN_ALL'