it('visits the app', () => {
  cy.visit('/')
})

describe('Home page', () => {
  beforeEach(() => {
    cy.visit('/')
  })

  it('keypad and display check ', () => {
    cy.get('.KvFtv').children().should('have.length', 20)
    cy.contains('7').dblclick()
    cy.get('.hVPVAJ div').should('have.text', '77')
    cy.contains('+').click()
    cy.contains('2').click()
    cy.contains('1').click()
    cy.get('.hVPVAJ div').should('have.text', '21')
    cy.contains('-').click()
    cy.get('.hVPVAJ div').should('have.text', '98')
    cy.contains('4').click()
    cy.contains('3').dblclick()
    cy.get('.hVPVAJ div').should('have.text', '433')
    cy.contains('CE').click()
    cy.get('.hVPVAJ div').should('have.text', '43')
    cy.contains('*').click()
    cy.get('.hVPVAJ div').should('have.text', '55')
    cy.contains('2').click()
    cy.get('.hVPVAJ div').should('have.text', '2')
    cy.contains('/').click()
    cy.get('.hVPVAJ div').should('have.text', '110')
    cy.contains('9').click()
    cy.contains('=').click()
    cy.get('.hVPVAJ div').should('have.text', '12.222')
    cy.contains('3').click()
    cy.contains('.').click()
    cy.contains('7').click()
    cy.contains('+/-').click()
    cy.get('.hVPVAJ div').should('have.text', '-3.7')
    cy.contains('+').click()
    cy.contains('2').click()
    cy.contains('.').click()
    cy.contains('3').click()
    cy.contains('+/-').click()
    cy.get('.hVPVAJ div').should('have.text', '-2.3')
    cy.contains('%').click()
    cy.get('.hVPVAJ div').should('have.text', '-6')
    cy.contains('+/-').click()
    cy.get('.hVPVAJ div').should('have.text', '6')
    cy.contains('5').click()
    cy.get('.hVPVAJ div').should('have.text', '5')
    cy.contains('=').click()
    cy.get('.hVPVAJ div').should('have.text', '1')
    cy.contains('C').click()
    cy.get('.hVPVAJ div').should('have.text', '0')
  })

  // it('check the keypad', () => {
  //   cy.get('ul').children().should('have.length', 22)
  // })

  // it('it check welcome title', () => {
  //   cy.get('#welcome')
  //     .should('be.visible')
  //     .contains('Welcome!')
  // })
})
